USE [master]
GO

/****** Object:  Database [ServicesDB]    Script Date: 17.02.2016 11:49:23 ******/
CREATE DATABASE [ServicesDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Services', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\Services.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Services_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\Services_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [ServicesDB] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ServicesDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ServicesDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ServicesDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ServicesDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ServicesDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ServicesDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [ServicesDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [ServicesDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ServicesDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ServicesDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ServicesDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ServicesDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ServicesDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ServicesDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ServicesDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ServicesDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [ServicesDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ServicesDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ServicesDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ServicesDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ServicesDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ServicesDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ServicesDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ServicesDB] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [ServicesDB] SET  MULTI_USER 
GO

ALTER DATABASE [ServicesDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ServicesDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ServicesDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [ServicesDB] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [ServicesDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [ServicesDB] SET  READ_WRITE 
GO

