//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Services.businessLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Service()
        {
            this.ServiceTypes = new HashSet<ServiceType>();
        }
    
        public int Id { get; set; }
        public string ServiceName { get; set; }
        public Nullable<double> UnitPrice { get; set; }
        public double NetPrice { get; set; }
        public int Vat { get; set; }
        public double VatAmount { get; set; }
        public double PretaxPrice { get; set; }
        public Nullable<int> FaVatPosition { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceType> ServiceTypes { get; set; }
    }
}
